import React from 'react';
// import ReactDOM from 'react-dom';
import styles from './new.module.css'
const News = () => {
    return (
        <div className={styles.container}>
            <h3 className={styles.content}>The cost of inaction: COVID-19-related service disruptions could cause hundreds of thousands of extra deaths from HIV</h3>
            <hr></hr>
            <img className={styles.image} src="https://media.npr.org/assets/img/2020/04/28/gettyimages-1205434458_custom-f366f2b88c56a0d8791d964607b2b81c29291d0c-s800-c85.jpg"></img>
            <img className={styles.image} src="https://cdn.vox-cdn.com/thumbor/0qESySOf_DjGUFlQjQnn5qwtKFE=/0x0:3360x2480/920x613/filters:focal(1412x972:1948x1508):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/66483505/1202995435.jpg.0.jpg"></img>
            <h4 className={styles.content}> Gains made in preventing mother-to-child transmission of HIV could be reversed, with new HIV infections among children up by as much as 104%</h4>
            <hr />
            <p className={styles.content}>A modelling group convened by the World Health Organization and UNAIDS has estimated that if efforts are not made to mitigate and overcome interruptions in health services and supplies during the COVID-19 pandemic, a six-month disruption of antiretroviral therapy could lead to more than 500 000 extra deaths from AIDS-related illnesses, including from tuberculosis, in sub-Saharan Africa in 2020–2021. In 2018, an estimated 470 000 people died of AIDS-related deaths in the region.<br /><br />
                There are many different reasons that could cause services to be interrupted—this modelling exercise makes it clear that communities and partners need to take action now as the impact of a six-month disruption of antiretroviral therapy could effectively set the clock on AIDS-related deaths back to 2008, when more than 950 000 AIDS-related deaths were observed in the region. And people would continue to die from the disruption in large numbers for at least another five years, with an annual average excess in deaths of 40% over the next half a decade. In addition, HIV service disruptions could also have some impact on HIV incidence in the next year.<br /><br />
                “The terrible prospect of half a million more people in Africa dying of AIDS-related illnesses is like stepping back into history,” said Dr Tedros Adhanom Ghebreyesus, Director-General of the World Health Organization.<br /><br />
                “We must read this as a wake-up call to countries to identify ways to sustain all vital health services. For HIV, some countries are already taking important steps, for example ensuring that people can collect bulk packs of treatment, and other essential commodities, including self-testing kits, from drop-off points, which relieves pressure on health services and the health workforce. We must also ensure that global supplies of tests and treatments continue to flow to the countries that need them,” added Dr Tedros.<br /><br />
                In sub-Saharan Africa, an estimated 25.7 million people were living with HIV and 16.4 million (64%) were taking antiretroviral therapy in 2018. Those people now risk having their treatment interrupted because HIV services are closed or are unable to supply antiretroviral therapy because of disruptions to the supply chain or because services simply become overwhelmed due to competing needs to support the COVID-19 response.<br /><br />
                “The COVID-19 pandemic must not be an excuse to divert investment from HIV,” said Winnie Byanyima, Executive Director of UNAIDS. “There is a risk that the hard-earned gains of the AIDS response will be sacrificed to the fight against COVID-19, but the right to health means that no one disease should be fought at the expense of the other.”<br /><br />
                When treatment is adhered to, a person’s HIV viral load drops to an undetectable level, keeping that person healthy and preventing onward transmission of the virus. When a person is unable to take antiretroviral therapy regularly, the viral load increases, impacting the person’s health, which can ultimately lead to death. Even relatively short-term interruptions to treatment can have a significant negative impact on a person’s health and potential to transmit HIV.<br /><br />
                This research brought together five teams of modellers using different mathematical models to analyse the effects of various possible disruptions to HIV testing, prevention and treatment services caused by COVID-19.< br /> <br />
                Each model looked at the potential impact of treatment disruptions of three months or six months on AIDS mortality and HIV incidence in sub-Saharan Africa. In the six-month disruption scenario, estimates of excess AIDS-related deaths in one year ranged from 471 000 to 673 000, making it inevitable that the world will miss the global 2020 target of fewer than 500 000 AIDS-related deaths worldwide.<br /><br />
                Shorter disruptions of three months would see a reduced but still significant impact on HIV deaths. More sporadic interruptions of antiretroviral therapy supply would lead to sporadic adherence to treatment, leading to the spread of HIV drug resistance, with long-term consequences for future treatment success in the region.<br /><br />
                Disrupted services could also reverse gains made in preventing mother-to-child transmission of HIV. Since 2010, new HIV infections among children in sub-Saharan Africa have declined by 43%, from 250 000 in 2010 to 140 000 in 2018, owing to the high coverage of HIV services for mothers and their children in the region. Curtailment of these services by COVID-19 for six months could see new child HIV infections rise drastically, by as much as 37% in Mozambique, 78% in Malawi, 78% in Zimbabwe and 104% in Uganda.<br /><br />
                Other significant effects of the COVID-19 pandemic on the AIDS response in sub-Saharan Africa that could lead to additional mortality include reduced quality clinical care owing to health facilities becoming overstretched and a suspension of viral load testing, reduced adherence counselling and drug regimen switches. Each model also considered the extent to which a disruption to prevention services, including suspension of voluntary medical male circumcision, interruption of condom availability and suspension of HIV testing, would impact HIV incidence in the region.<br /><br />
                The research highlights the need for urgent efforts to ensure the continuity of HIV prevention and treatment services in order to avert excess HIV-related deaths and to prevent increases in HIV incidence during the COVID-19 pandemic. It will be important for countries to prioritize shoring up supply chains and ensuring that people already on treatment are able to stay on treatment, including by adopting or reinforcing policies such as multimonth dispensing of antiretroviral therapy in order to reduce requirements to access health-care facilities for routine maintenance, reducing the burden on overwhelmed health-care systems.<br /><br />
                “Every death is a tragedy,” added Ms Byanyima. “We cannot sit by and allow hundreds of thousands of people, many of them young, to die needless deaths. I urge governments to ensure that every man, women and child living with HIV gets regular supplies of antiretroviral therapy—something that’s literally a life-saver.”
            </p>




        </div>
    )

}
export default News;